services:
  # 1. The FastAPI Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env 
    volumes:
      - telemetry_data:/app/telemetry.db 

  # 2. The Vanilla Frontend
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./style.css:/usr/share/nginx/html/style.css
      - ./app.js:/usr/share/nginx/html/app.js
      - ./terminal_art.jpg:/usr/share/nginx/html/terminal_art.jpg
    depends_on:
      - backend

volumes:
  telemetry_data: