name: Automated Knowledge Base Ingestion

on:
  schedule:
    # runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch: # allows to manually click "Run Workflow" on github

permissions: 
  contents: write # permision to commit files back to repo

jobs:
  update-vector-db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' #speeds up consecutive runs
          cache-dependency-path: 'backend/requirements.txt'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Nexus Mods Ingestion Script
        run: python build_pipeline_NM.py
        env:
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        
      - name: Commit and Push State Trackers
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Nexus Mods ingestion tracking queues and BM25 dictionary"
          # update the mods list that's in queue, what we've processed, and the BM25 dicitonary
          file_pattern: "mod_queue.txt processed_mods.txt chunks.pkl" 