name: Automated Knowledge Base Ingestion

on:
  schedule:
    # runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch: # allows to manually click "Run Workflow" on github

permissions: 
  contents: write # permision to commit files back to repo

jobs:
  update-vector-db:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' #speeds up consecutive runs

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run Data Ingestion Script
        # executes the file in the services.py to rebuild the DB
        run: python build_pipeline.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          # required for gemini model

      - name: Run Nexus Mods Ingestion Script
        run: python build_pipeline_NM.py
        env:
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
        
      - name: Commit and Push Updated Vector DB
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update Chroma DB (Base + Nexus Mods)"
          file_pattern: "vnv_chroma_db/*" # targets the DB directory